import 'package:freezed_annotation/freezed_annotation.dart';

part 'bible_book.freezed.dart';

/// Книги и число глав сверены с https://azbyka.ru/biblia/ (25.09.2026).
/// Каталог локальный, чтобы выбор книги работал до первого сетевого ответа.
@freezed
abstract class BibleBook with _$BibleBook {
  const factory BibleBook(String code, String title, int chapterCount) =
      _BibleBook;
}

const bibleBooks = <BibleBook>[
  BibleBook('Gen', 'Бытие', 50),
  BibleBook('Ex', 'Исход', 40),
  BibleBook('Lev', 'Левит', 27),
  BibleBook('Num', 'Числа', 36),
  BibleBook('Deut', 'Второзаконие', 34),
  BibleBook('Nav', 'Иисуса Навина', 24),
  BibleBook('Judg', 'Судей Израилевых', 21),
  BibleBook('Rth', 'Руфь', 4),
  BibleBook('1Sam', 'Царств 1-я', 31),
  BibleBook('2Sam', 'Царств 2-я', 24),
  BibleBook('1King', 'Царств 3-я', 22),
  BibleBook('2King', 'Царств 4-я', 25),
  BibleBook('1Chron', 'Паралипоменон 1-я', 29),
  BibleBook('2Chron', 'Паралипоменон 2-я', 36),
  BibleBook('Ezr', 'Ездры 1-я', 10),
  BibleBook('2Ezr', 'Ездры 2-я', 9),
  BibleBook('Nehem', 'Неемии', 13),
  BibleBook('Tov', 'Товит', 14),
  BibleBook('Judf', 'Иудифь', 16),
  BibleBook('Est', 'Есфирь', 10),
  BibleBook('1Mac', 'Маккавейская 1-я', 16),
  BibleBook('2Mac', 'Маккавейская 2-я', 15),
  BibleBook('3Mac', 'Маккавейская 3-я', 7),
  BibleBook('Job', 'Иова', 42),
  BibleBook('Ps', 'Псалтирь', 151),
  BibleBook('Prov', 'Притчей Соломоновых', 31),
  BibleBook('Eccl', 'Екклезиаста', 12),
  BibleBook('Song', 'Песни Песней Соломона', 8),
  BibleBook('Solom', 'Премудрости Соломона', 19),
  BibleBook('Sir', 'Премудрости Иисуса, сына Сирахова', 51),
  BibleBook('Is', 'Исаии', 66),
  BibleBook('Jer', 'Иеремии', 52),
  BibleBook('Lam', 'Плач Иеремии', 5),
  BibleBook('pJer', 'Послание Иеремии', 1),
  BibleBook('Bar', 'Варуха', 5),
  BibleBook('Ezek', 'Иезекииля', 48),
  BibleBook('Dan', 'Даниила', 14),
  BibleBook('Hos', 'Осии', 14),
  BibleBook('Joel', 'Иоиля', 3),
  BibleBook('Am', 'Амоса', 9),
  BibleBook('Avd', 'Авдия', 1),
  BibleBook('Jona', 'Ионы', 4),
  BibleBook('Mic', 'Михея', 7),
  BibleBook('Naum', 'Наума', 3),
  BibleBook('Habak', 'Аввакума', 3),
  BibleBook('Sofon', 'Софонии', 3),
  BibleBook('Hag', 'Аггея', 2),
  BibleBook('Zah', 'Захарии', 14),
  BibleBook('Mal', 'Малахии', 4),
  BibleBook('3Ezr', 'Ездры 3-я', 16),
  BibleBook('Mt', 'От Матфея', 28),
  BibleBook('Mk', 'От Марка', 16),
  BibleBook('Lk', 'От Луки', 24),
  BibleBook('Jn', 'От Иоанна', 21),
  BibleBook('Act', 'Деяния святых Апостолов', 28),
  BibleBook('Jac', 'Иакова', 5),
  BibleBook('1Pet', 'Петра 1-е', 5),
  BibleBook('2Pet', 'Петра 2-е', 3),
  BibleBook('1Jn', 'Иоанна 1-е', 5),
  BibleBook('2Jn', 'Иоанна 2-е', 1),
  BibleBook('3Jn', 'Иоанна 3-е', 1),
  BibleBook('Juda', 'Иуды', 1),
  BibleBook('Rom', 'К римлянам', 16),
  BibleBook('1Cor', 'К коринфянам 1-е', 16),
  BibleBook('2Cor', 'К коринфянам 2-е', 13),
  BibleBook('Gal', 'К галатам', 6),
  BibleBook('Eph', 'К ефесянам', 6),
  BibleBook('Phil', 'К филиппийцам', 4),
  BibleBook('Col', 'К колоссянам', 4),
  BibleBook('1Thes', 'К фессалоникийцам 1-е', 5),
  BibleBook('2Thes', 'К фессалоникийцам 2-е', 3),
  BibleBook('1Tim', 'К Тимофею 1-е', 6),
  BibleBook('2Tim', 'К Тимофею 2-е', 4),
  BibleBook('Tit', 'К Титу', 3),
  BibleBook('Phlm', 'К Филимону', 1),
  BibleBook('Hebr', 'К евреям', 13),
  BibleBook('Apok', 'Откровение Иоанна Богослова (Апокалипсис)', 22),
];
