name: CI

on:
  pull_request:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  verify:
    runs-on: ubuntu-24.04
    steps:
      - name: Проверить исходный код
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Установить Flutter
        uses: subosito/flutter-action@1a449444c387b1966244ae4d4f8c696479add0b2 # v2.23.0
        with:
          channel: stable
          flutter-version: 3.44.8

      - name: Получить зависимости
        run: flutter pub get

      - name: Проверить форматирование
        run: dart format --output=none --set-exit-if-changed .

      - name: Проверить Dart-код
        run: flutter analyze

      - name: Запустить Flutter-тесты
        run: flutter test

      - name: Проверить workflow
        uses: docker://rhysd/actionlint@sha256:1d74bfc9fd1963af8f89a7c22afaaafd42f49aad711a09951d02cb996398f61d # v1.7.7 linux/amd64
